MedicinaPrepagada/Models/DBMedicinaPrepagada/Source/Cuentas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public int id_cuenta { get; set; }
        public int id_ips { get; set; }
        public int id_orden { get; set; }
        public System.DateTime fecha_periodo_ini { get; set; }
        public System.DateTime fecha_periodo_fin { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public double valor_a_pagar { get; set; }
        public string estado { get; set; }
        public int pagado { get; set; }
    }
}

MedicinaPrepagada/Controllers/CuentaController.cs
using MedicinaPrepagada.Models.DBMedicinaPrepagada.Source;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace MedicinaPrepagada.Controllers
{
    public class CuentaController : Controller
    {
        private DBPrepagadaEntities db = new DBPrepagadaEntities();
        // GET: Cuentas
        public ActionResult Index()
        {
            return View();
        }

        // GET: Cuentas/Details/5
        public ActionResult Details()
        {
            try
            {
                return View(db.CuentasXPagar.ToList());
            }catch(Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
            
           
        }

        // GET: Cuentas/Create
        public ActionResult Plano()
        {
            return View();
        }

        // Post subir archivo plano
        [HttpPost]
        public ActionResult Plano(HttpPostedFileBase file)
        {
            try
            {
                string linea;
                char delimeter = ';';

                if (file == null)
                {
                    return View();
                }
                else
                {
                    while ((linea = new StreamReader(file.InputStream).ReadLine()) != null)
                    {
                        string[] subLinea = linea.Split(delimeter);
                        bool isOk = validacion(subLinea.Length, subLinea);
                        if (isOk == false)
                        {
                            //ViewBag.Javascript = ("<Script lenguage= 'javaScript' type = 'text/javaScript'>alert('Revise el archivo de texto, Archivo no valido');</Script>");

                            //ViewData["message"] = "<Script lenguage= 'javaScript' type = 'text/javaScript'>alert('Revise el archivo de texto, Archivo no valido');</Script>";
                            ViewData["message"] = " el archivo de texto, Archivo no valido";
                            return View();
                        }
                        else
                        {
                            DateTime fecha_ini = Convert.ToDateTime(subLinea[0]);
                            DateTime fecha_fin = Convert.ToDateTime(subLinea[1]);
                            int id_ips = int.Parse(subLinea[2]);
                            float valor = float.Parse(subLinea[3]);
                            save(fecha_ini, fecha_fin, id_ips, valor);
                        }
                    }
                }
            }
            catch (Exception ex)

            {
                return View();
            }
            return View();
        }

        public bool validacion(int tamaño,String[] inf)
        {
            DateTime f1;
            int num1;
            float sal;
            if (tamaño == 4 )
             
            {
                if(DateTime.TryParse(inf[0], out f1))
                //if(Regex.IsMatch(inf[0], "[1|2|3]["))
                {
                    if(DateTime.TryParse(inf[1], out f1))
                    {
                        if(int.TryParse(inf[2], out num1))
                        {
                           
                                if (float.TryParse(inf[3], out sal))
                                {
                                    return true;
                                }
                            }
                        }
                       
                    


                }
                
            }
            return false;

        }
        

        //este metodo guarda 
        public bool save(DateTime fecha_ini, DateTime fecha_fin, int ips, float valor)
        {
            try
            {
                CuentasXPagar cuentas = new CuentasXPagar();
                cuentas.fecha_periodo_ini = fecha_ini;
                cuentas.fecha_periodo_fin = fecha_fin;
                cuentas.id_ips = ips;
                

                cuentas.valor_a_pagar = valor;
                cuentas.estado = "0";
                cuentas.pagado = 0;

                //orde los datos
                db.CuentasXPagar.Add(cuentas);
                db.SaveChanges();
                
                return true;
            }
            catch(Exception ex)
            
            {
                return false;
            }
           

            
        }

        // POST: Cuentas/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cuentas/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                CuentasXPagar cuentaTempo = db.CuentasXPagar.Find(id);
                if(cuentaTempo == null)
                {
                    return HttpNotFound();
                }
                return View(cuentaTempo);
            }
            catch(Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
        }

        // POST: Cuentas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cuentas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cuentas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MedicinaPrepagada/Views/Cuenta/Details.cshtml
@model  IEnumerable<MedicinaPrepagada.Models.DBMedicinaPrepagada.Source.CuentasXPagar>


@{
    ViewBag.Title = "Details";
}




<h2>Listar</h2>

</select>
    <p>
        <table class="table">
            <tr>
                <th>
                    Fecha Inicio
                </th>
                <th>
                    Fecha Fin
                </th>
                <th>
                    IPS
                </th>
                <th>
                    Autorizado
                </th>
                <th>
                    Valor
                </th>
                <th></th>
            </tr>
          

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.fecha_periodo_ini)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fecha_periodo_fin)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.id_ips)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.estado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.valor_a_pagar)
                    </td>
                    <td>
                        @Html.ActionLink("Autorizar", "Edit", new { id = item.id_cuenta })
                    </td>
                </tr>
            }
        </table>
    </p>

MedicinaPrepagada/Views/Cuenta/Edit.cshtml
@model MedicinaPrepagada.Models.DBMedicinaPrepagada.Source.CuentasXPagar


@{
    ViewBag.Title = "Edit";
}

<h2>Autorizar</h2>
<script type="text/javascript">

    $(document).ready(function () {
        var n = "@Html.DisplayFor( model=>model.estado)";
        alert(n);
    })
</script>

@using (Html.BeginForm())
{
    <div class= "form-horizontal">
        <h4>Cuentas por Pagar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger"})
        @Html.HiddenFor(model => model.id_cuenta)

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_periodo_ini, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_periodo_ini, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_periodo_ini, "", new { @class = "text-danger"})
            </div>
            

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_periodo_fin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_periodo_fin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_periodo_fin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_ips, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_ips, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_ips, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("1","Choose")
                <select id="cboAut" class="form-control" value="@Html.DisplayFor( model=>model.estado)">
                    <option value="1">Autorizado</option>
                    <option value="0">No Autorizado</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.valor_a_pagar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.valor_a_pagar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.valor_a_pagar, "", new { @class = "text-danger" })
            </div>
        </div>


    </div>
}

MedicinaPrepagada/Views/Cuenta/Plano.cshtml
@{
    ViewBag.Title = "Plano";
}

<h2>Plano</h2>


@using (Html.BeginForm("Plano", "Cuenta", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input id="file" type="file" name="file" />
    <button type="submit"> Subir Archivo</button>
    
}
<p style="color:red;">@ViewData["message"]</p>

<p>
    @Html.ActionLink("Validar Cuenta", "Details")
</p>